### ISSUE TITLE
4s-8s model?

### ISSUE THREAD

**Issue by nebulight** [NEEY-ELEC/NEEY-BALANCER#1]
Sorry to post this here but do you know if the 4-8s model is out yet? And where to buy? Thank you!

**Comment by NEEY-ELEC** [comment]
Dear, thank you for your consultation. We will produce intelligent balancers supporting 4-10s and 8-17s by the end of this year，please follow our store we will give the latest news to you
have a nice day
best regards



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年09月28日 13:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [NEEY-ELEC/NEEY-BALANCER] 4s-8s model? (#1) |

Sorry to post this here but do you know if the 4-8s model is out yet? And where to buy? Thank you!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nebulight** [comment]
Can you post a url to your store? I found out about your product via a YouTube video. Thanks.

**Comment by NEEY-ELEC** [comment]
https://www.aliexpress.com/item/1005003125644284.html



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年09月28日 21:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NEEY-ELEC/NEEY-BALANCER] 4s-8s model? (#1) |

Can you post a url to your store? I found out about your product via a YouTube video. Thanks.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
